import { useState, useEffect, useRef, useCallback } from "react";
import { Link, useNavigate } from "react-router";
import { ArrowLeft, Download, Share2, Home, Sparkles, Move, RotateCw, ZoomIn, Palette, Loader2, Wand2 } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import GlassCard from "../components/GlassCard";
import { triggerHaptic } from "../utils/haptics";
import { getGeminiAI } from "../utils/geminiConfig";

export default function HairstyleResult() {
  const navigate = useNavigate();
  const [sliderPosition, setSliderPosition] = useState(50);
  const [showSuccess, setShowSuccess] = useState(true);
  const [showAdjustments, setShowAdjustments] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [aiResultUrl, setAiResultUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  
  // Hairstyle overlay adjustments
  const [hairstylePosition, setHairstylePosition] = useState({ x: 0, y: -20 });
  const [hairstyleScale, setHairstyleScale] = useState(1.2);
  const [hairstyleRotation, setHairstyleRotation] = useState(0);
  const [hairstyleOpacity, setHairstyleOpacity] = useState(0.9);
  
  // Get data from sessionStorage
  const facePhoto = sessionStorage.getItem("hairstyle_facePhoto") || "";
  const selectedStyle = JSON.parse(sessionStorage.getItem("hairstyle_selectedStyle") || "{}");
  const selectedColor = JSON.parse(sessionStorage.getItem("hairstyle_selectedColor") || "{}");

  useEffect(() => {
    // Success animation
    const timeout = setTimeout(() => {
      setShowSuccess(false);
    }, 3000);

    return () => clearTimeout(timeout);
  }, []);

  const generateAiLook = useCallback(async () => {
    if (!facePhoto || !selectedStyle.imageUrl) return;

    try {
      setIsGenerating(true);
      setError(null);
      const ai = getGeminiAI();

      // Convert face photo to base64 part
      const faceBase64 = facePhoto.split(',')[1];
      const facePart = {
        inlineData: {
          data: faceBase64,
          mimeType: "image/png"
        }
      };

      // Fetch hairstyle reference image and convert to base64
      const hairResponse = await fetch(selectedStyle.imageUrl);
      const hairBlob = await hairResponse.blob();
      const hairBase64 = await new Promise<string>((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve((reader.result as string).split(',')[1]);
        reader.readAsDataURL(hairBlob);
      });
      const hairPart = {
        inlineData: {
          data: hairBase64,
          mimeType: hairBlob.type
        }
      };

      const prompt = `Change the hairstyle of the person in the base image to the hairstyle shown in the reference image. 
      The hairstyle is a ${selectedStyle.name} (${selectedStyle.category}) in ${selectedColor.name} color. 
      Maintain the person's facial features, skin tone, and background. 
      Only modify the hair to match the reference style and specified color. 
      Make it look extremely realistic and naturally blended.`;

      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash-image",
        contents: {
          parts: [
            { text: "Base image (person):" },
            facePart,
            { text: "Reference image (hairstyle):" },
            hairPart,
            { text: prompt }
          ]
        }
      });

      let generatedImageUrl = null;
      for (const candidate of response.candidates || []) {
        for (const part of candidate.content.parts) {
          if (part.inlineData) {
            generatedImageUrl = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
            break;
          }
        }
        if (generatedImageUrl) break;
      }

      if (generatedImageUrl) {
        setAiResultUrl(generatedImageUrl);
        triggerHaptic("success");
      } else {
        throw new Error("No image was generated by the AI.");
      }
    } catch (err: any) {
      console.error("AI Generation Error:", err);
      setError("Failed to generate AI look. Using manual overlay instead.");
    } finally {
      setIsGenerating(false);
    }
  }, [facePhoto, selectedStyle, selectedColor]);

  useEffect(() => {
    generateAiLook();
  }, [generateAiLook]);

  useEffect(() => {
    // Draw the hairstyle overlay on canvas
    if (canvasRef.current && facePhoto && selectedStyle.imageUrl) {
      const canvas = canvasRef.current;
      const ctx = canvas.getContext("2d");
      if (!ctx) return;

      const faceImg = new Image();
      faceImg.crossOrigin = "anonymous";
      faceImg.src = facePhoto;

      faceImg.onload = () => {
        // Set canvas dimensions
        canvas.width = 390;
        canvas.height = 500;

        // Draw face photo
        ctx.drawImage(faceImg, 0, 0, canvas.width, canvas.height);

        // Load and draw hairstyle
        const hairImg = new Image();
        hairImg.crossOrigin = "anonymous";
        hairImg.src = selectedStyle.imageUrl;

        hairImg.onload = () => {
          ctx.save();
          
          // Apply transformations
          ctx.globalAlpha = hairstyleOpacity;
          ctx.translate(
            canvas.width / 2 + hairstylePosition.x,
            canvas.height / 3 + hairstylePosition.y
          );
          ctx.rotate((hairstyleRotation * Math.PI) / 180);
          ctx.scale(hairstyleScale, hairstyleScale);
          
          // Draw hairstyle (centered)
          const hairWidth = canvas.width * 0.8;
          const hairHeight = (hairImg.height / hairImg.width) * hairWidth;
          ctx.drawImage(hairImg, -hairWidth / 2, -hairHeight / 2, hairWidth, hairHeight);
          
          // Apply color tint
          if (selectedColor.hex && selectedColor.hex !== "transparent") {
            ctx.globalCompositeOperation = "multiply";
            ctx.fillStyle = selectedColor.hex;
            ctx.fillRect(-hairWidth / 2, -hairHeight / 2, hairWidth, hairHeight);
          }
          
          ctx.restore();
        };
      };
    }
  }, [facePhoto, selectedStyle, selectedColor, hairstylePosition, hairstyleScale, hairstyleRotation, hairstyleOpacity]);

  const handleSaveToMyLooks = () => {
    const saved = JSON.parse(localStorage.getItem("my_looks") || "[]");
    const newLook = {
      id: Date.now().toString(),
      type: "hairstyle",
      image: aiResultUrl || canvasRef.current?.toDataURL() || "",
      hairstyleName: selectedStyle.name,
      date: new Date().toISOString(),
    };
    saved.push(newLook);
    localStorage.setItem("my_looks", JSON.stringify(saved));
    triggerHaptic("success");
  };

  const handleDownload = () => {
    const imageUrl = aiResultUrl || canvasRef.current?.toDataURL();
    if (imageUrl) {
      const link = document.createElement("a");
      link.download = `hairstyle-tryon-${Date.now()}.png`;
      link.href = imageUrl;
      link.click();
      triggerHaptic("success");
    }
  };

  const handleWhatsAppShare = () => {
    const text = `Thinking of getting this haircut 😎\nWhat do you think?\n\nTry it yourself at TryOn AI ✨`;
    const url = `https://wa.me/?text=${encodeURIComponent(text)}`;
    window.open(url, "_blank");
  };

  const resultImageUrl = aiResultUrl || canvasRef.current?.toDataURL() || selectedStyle.imageUrl;

  return (
    <div className="min-h-screen bg-[#0f0f13] text-white">
      <div className="max-w-[390px] mx-auto relative">
        {/* Hidden canvas for rendering */}
        <canvas ref={canvasRef} className="hidden" />

        {/* AI Generating Overlay */}
        <AnimatePresence>
          {isGenerating && (
            <motion.div
              className="absolute inset-0 z-40 bg-black/60 backdrop-blur-md flex flex-col items-center justify-center p-8 text-center"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            >
              <div className="relative">
                <div className="w-20 h-20 rounded-full border-4 border-[#ec4899]/20 border-t-[#ec4899] animate-spin mb-6" />
                <Wand2 className="w-8 h-8 text-[#ec4899] absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 animate-pulse" />
              </div>
              <h3 className="text-xl font-bold mb-2 bg-gradient-to-r from-[#ec4899] to-[#f97316] bg-clip-text text-transparent">
                AI Magic in Progress...
              </h3>
              <p className="text-sm text-[#a1a1aa]">
                Our AI is carefully crafting your new hairstyle. This will just take a moment.
              </p>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Success Animation */}
        <AnimatePresence>
          {showSuccess && (
            <motion.div
              className="fixed inset-0 z-50 pointer-events-none flex items-center justify-center"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            >
              <motion.div
                className="text-center"
                initial={{ scale: 0, rotate: -180 }}
                animate={{ scale: 1, rotate: 0 }}
                exit={{ scale: 0, rotate: 180 }}
                transition={{ type: "spring", duration: 0.8 }}
              >
                <div
                  className="w-24 h-24 rounded-full bg-gradient-to-br from-[#ec4899] to-[#f97316] flex items-center justify-center mb-4 mx-auto"
                  style={{ boxShadow: "0 0 60px rgba(236, 72, 153, 0.8)" }}
                >
                  <Sparkles className="w-12 h-12" />
                </div>
                <h2 className="text-[28px] font-bold">Perfect! ✨</h2>
                <p className="text-[#a1a1aa]">Your new look is ready</p>
              </motion.div>

              {/* Confetti */}
              {[...Array(30)].map((_, i) => (
                <motion.div
                  key={i}
                  className="absolute w-2 h-2 rounded-full"
                  style={{
                    backgroundColor: i % 3 === 0 ? "#ec4899" : i % 3 === 1 ? "#f97316" : "#22c55e",
                    left: "50%",
                    top: "50%",
                  }}
                  initial={{ scale: 0, x: 0, y: 0 }}
                  animate={{
                    scale: [0, 1, 0.5],
                    x: (Math.random() - 0.5) * 400,
                    y: (Math.random() - 0.5) * 400,
                    opacity: [1, 1, 0],
                  }}
                  transition={{
                    duration: 1.5,
                    delay: i * 0.03,
                  }}
                />
              ))}
            </motion.div>
          )}
        </AnimatePresence>

        {/* Header */}
        <div className="sticky top-0 z-10 backdrop-blur-xl bg-[#0f0f13]/80 border-b border-white/10">
          <div className="flex items-center justify-between px-6 py-4">
            <Link to="/hairstyle-selection">
              <motion.button
                className="w-10 h-10 rounded-full bg-white/10 flex items-center justify-center"
                whileTap={{ scale: 0.95 }}
              >
                <ArrowLeft className="w-5 h-5" />
              </motion.button>
            </Link>
            <h1 className="font-semibold">Your New Look</h1>
            <Link to="/">
              <motion.button
                className="w-10 h-10 rounded-full bg-white/10 flex items-center justify-center"
                whileTap={{ scale: 0.95 }}
              >
                <Home className="w-5 h-5" />
              </motion.button>
            </Link>
          </div>
        </div>

        {/* Before/After Comparison Slider */}
        <motion.div
          className="relative h-[500px] overflow-hidden"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
        >
          {/* Before Image */}
          <div className="absolute inset-0">
            <img src={facePhoto} alt="Before" className="w-full h-full object-cover" />
            <div className="absolute top-4 left-4 px-3 py-1.5 bg-black/60 backdrop-blur-sm rounded-full text-[13px] font-medium">
              Before
            </div>
          </div>

          {/* After Image with Clip */}
          <div className="absolute inset-0" style={{ clipPath: `inset(0 ${100 - sliderPosition}% 0 0)` }}>
            <img src={resultImageUrl} alt="After" className="w-full h-full object-cover" />
            <div className="absolute top-4 right-4 px-3 py-1.5 bg-gradient-to-r from-[#ec4899] to-[#f97316] backdrop-blur-sm rounded-full text-[13px] font-medium">
              After ✨
            </div>
          </div>

          {/* Slider Handle */}
          <div
            className="absolute top-0 bottom-0 w-1 bg-white cursor-ew-resize z-20"
            style={{ left: `${sliderPosition}%` }}
            onMouseDown={(e) => {
              const parentElement = e.currentTarget.parentElement;
              const handleMove = (moveEvent: MouseEvent) => {
                if (parentElement) {
                  const rect = parentElement.getBoundingClientRect();
                  const x = moveEvent.clientX - rect.left;
                  const percentage = Math.max(0, Math.min(100, (x / rect.width) * 100));
                  setSliderPosition(percentage);
                }
              };
              const handleUp = () => {
                document.removeEventListener("mousemove", handleMove);
                document.removeEventListener("mouseup", handleUp);
              };
              document.addEventListener("mousemove", handleMove);
              document.addEventListener("mouseup", handleUp);
            }}
            onTouchStart={(e) => {
              const parentElement = e.currentTarget.parentElement;
              const handleMove = (moveEvent: TouchEvent) => {
                if (parentElement) {
                  const rect = parentElement.getBoundingClientRect();
                  const x = moveEvent.touches[0].clientX - rect.left;
                  const percentage = Math.max(0, Math.min(100, (x / rect.width) * 100));
                  setSliderPosition(percentage);
                }
              };
              const handleUp = () => {
                document.removeEventListener("touchmove", handleMove);
                document.removeEventListener("touchend", handleUp);
              };
              document.addEventListener("touchmove", handleMove);
              document.addEventListener("touchend", handleUp);
            }}
          >
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-12 h-12 bg-white rounded-full shadow-2xl flex items-center justify-center">
              <div className="flex gap-1">
                <div className="w-0.5 h-4 bg-[#0f0f13]" />
                <div className="w-0.5 h-4 bg-[#0f0f13]" />
              </div>
            </div>
          </div>
        </motion.div>

        {/* Info */}
        <div className="px-6 py-4">
          <GlassCard className="p-4">
            <div className="flex items-center gap-3 mb-2">
              <Sparkles className="w-5 h-5 text-[#ec4899]" />
              <div>
                <h3 className="font-semibold">{selectedStyle.name}</h3>
                <p className="text-[11px] text-[#a1a1aa]">
                  Color: {selectedColor.name} • {selectedStyle.category}
                </p>
              </div>
            </div>
            <p className="text-[13px] text-[#a1a1aa]">👆 Drag to compare before & after</p>
            {error && (
              <p className="text-[11px] text-orange-400 mt-2 flex items-center gap-1">
                <Sparkles className="w-3 h-3" />
                {error}
              </p>
            )}
          </GlassCard>
        </div>

        {/* Adjustments Toggle */}
        <div className="px-6 pb-4">
          <motion.button
            className="w-full h-[44px] rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center gap-2"
            whileTap={{ scale: 0.97 }}
            onClick={() => setShowAdjustments(!showAdjustments)}
          >
            <Move className="w-5 h-5" />
            {showAdjustments ? "Hide" : "Show"} Adjustments
          </motion.button>
        </div>

        {/* Adjustment Controls */}
        <AnimatePresence>
          {showAdjustments && (
            <motion.div
              className="px-6 pb-4 space-y-4"
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              exit={{ opacity: 0, height: 0 }}
            >
              <GlassCard className="p-4 space-y-4">
                {/* Position */}
                <div>
                  <label className="text-[13px] text-[#a1a1aa] mb-2 block flex items-center gap-2">
                    <Move className="w-4 h-4" />
                    Vertical Position
                  </label>
                  <input
                    type="range"
                    min="-100"
                    max="100"
                    value={hairstylePosition.y}
                    onChange={(e) => setHairstylePosition({ ...hairstylePosition, y: Number(e.target.value) })}
                    className="w-full"
                  />
                </div>

                {/* Scale */}
                <div>
                  <label className="text-[13px] text-[#a1a1aa] mb-2 block flex items-center gap-2">
                    <ZoomIn className="w-4 h-4" />
                    Size ({Math.round(hairstyleScale * 100)}%)
                  </label>
                  <input
                    type="range"
                    min="0.5"
                    max="2"
                    step="0.1"
                    value={hairstyleScale}
                    onChange={(e) => setHairstyleScale(Number(e.target.value))}
                    className="w-full"
                  />
                </div>

                {/* Rotation */}
                <div>
                  <label className="text-[13px] text-[#a1a1aa] mb-2 block flex items-center gap-2">
                    <RotateCw className="w-4 h-4" />
                    Rotation ({hairstyleRotation}°)
                  </label>
                  <input
                    type="range"
                    min="-30"
                    max="30"
                    value={hairstyleRotation}
                    onChange={(e) => setHairstyleRotation(Number(e.target.value))}
                    className="w-full"
                  />
                </div>

                {/* Opacity */}
                <div>
                  <label className="text-[13px] text-[#a1a1aa] mb-2 block flex items-center gap-2">
                    <Palette className="w-4 h-4" />
                    Blend ({Math.round(hairstyleOpacity * 100)}%)
                  </label>
                  <input
                    type="range"
                    min="0.3"
                    max="1"
                    step="0.1"
                    value={hairstyleOpacity}
                    onChange={(e) => setHairstyleOpacity(Number(e.target.value))}
                    className="w-full"
                  />
                </div>
              </GlassCard>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Action Buttons */}
        <div className="px-6 py-4 space-y-3 pb-8">
          <motion.button
            className="w-full h-[52px] rounded-full font-semibold flex items-center justify-center gap-2"
            style={{
              background: "linear-gradient(135deg, #ec4899 0%, #f97316 100%)",
              boxShadow: "0 0 30px rgba(236, 72, 153, 0.4)",
            }}
            whileTap={{ scale: 0.97 }}
            onClick={handleDownload}
          >
            <Download className="w-5 h-5" />
            Download Image
          </motion.button>

          <div className="grid grid-cols-2 gap-3">
            <motion.button
              className="h-[52px] rounded-full font-semibold flex items-center justify-center gap-2 bg-[#25D366]"
              whileTap={{ scale: 0.97 }}
              onClick={handleWhatsAppShare}
            >
              <Share2 className="w-5 h-5" />
              WhatsApp
            </motion.button>

            <motion.button
              className="h-[52px] rounded-full font-semibold flex items-center justify-center gap-2 bg-white/10 border border-white/20"
              whileTap={{ scale: 0.97 }}
              onClick={() => {
                handleSaveToMyLooks();
                navigate("/my-looks");
              }}
            >
              <Sparkles className="w-5 h-5" />
              Save Look
            </motion.button>
          </div>
        </div>

        {/* Try Another */}
        <div className="px-6 pb-8">
          <GlassCard className="p-6 text-center">
            <h3 className="font-semibold mb-2">Love it? Try another style!</h3>
            <p className="text-[13px] text-[#a1a1aa] mb-4">Experiment with different hairstyles & colors</p>
            <Link to="/hairstyle-selection">
              <button className="w-full h-[44px] rounded-full bg-white/10 hover:bg-white/20 transition-colors border border-white/20">
                Try Another Hairstyle
              </button>
            </Link>
          </GlassCard>
        </div>
      </div>
    </div>
  );
}
